package edu.ucue.tfc.GUI;

import edu.ucue.tfc.Dao.RegistrosDao;
import edu.ucue.tfc.Modelo.ControladorVideo;
import edu.ucue.tfc.Service.SeleccionArchivo;
import edu.ucue.tfc.Service.VideoService;

import java.io.IOException;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import org.opencv.core.Core;


/**
 *
 * @author Paul
 */
public class RegistroVideo extends javax.swing.JFrame
{
    public void finVideo() {
        JOptionPane.showMessageDialog(rootPane, "Video analizado totalmente, proceda a guardar");
        return;
    }
    
    public void setBarrarProgreso(int progreso) {
        this.barraProgreso.setValue(progreso);
    }
    
    public void setBtnReproducirText(String text) {
        this.btnReproducir.setText(text);
    }
    
    public void setLabelProgreso(String progreso) {
        this.labelTiempoTranscurrido.setText(progreso);
    }
    
    public void setTiempo() {
        labelTiempoTranscurrido.setText(RegistrosDao.getInstanciaRegistrosDao().getControladorVideo().
                                        getVideoProcessor().getActualLengthFormatted());
        labelTiempoTotal.setText(RegistrosDao.getInstanciaRegistrosDao().getControladorVideo().
                                getVideoProcessor().getLengthFormatted());
    }
    
    public void setEnableBtnReproducir(boolean bool) {
        this.btnReproducir.setEnabled(bool);
    }
    
    public void setEnableBtnParar(boolean bool) {
        this.btnParar.setEnabled(bool);
    }
    
    public void setEnableBtnGuardar(boolean bool) {
        this.btnGuardar.setEnabled(bool);
    }
    
    public void setEnableBtnAbrir(boolean bool) {
        this.btnAbrir.setEnabled(bool);    
    }
    
    public void setTexto(String text) {
        this.txtVideo.setText(text);
    }
    
    public RegistroVideo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReproducir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVideo = new javax.swing.JTextArea();
        btnParar = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        barraProgreso = new javax.swing.JProgressBar();
        labelTiempoTranscurrido = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        labelCaptura = new javax.swing.JLabel();
        labelTiempoTotal = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        btnAceptarCiudad = new javax.swing.JButton();
        btnAceptarCalle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Video");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setFocusTraversalPolicyProvider(true);

        btnReproducir.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        btnReproducir.setText("Reproducir");
        btnReproducir.setEnabled(false);
        btnReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirActionPerformed(evt);
            }
        });

        txtVideo.setColumns(20);
        txtVideo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtVideo.setRows(5);
        txtVideo.setText("\n\tNo se ha cargado un video!");
        txtVideo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtVideo.setEnabled(false);
        txtVideo.setOpaque(false);
        txtVideo.setRequestFocusEnabled(false);
        txtVideo.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtVideo.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(txtVideo);

        btnParar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        btnParar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/stop-1.png"))); // NOI18N
        btnParar.setText("Parar");
        btnParar.setEnabled(false);
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.setPreferredSize(new java.awt.Dimension(320, 240));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        btnGuardar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ucue/tfc/GUI/icons/save.png"))); // NOI18N
        btnGuardar.setText("Guardar Datos");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        barraProgreso.setBackground(new java.awt.Color(255, 255, 255));
        barraProgreso.setForeground(new java.awt.Color(51, 51, 255));

        labelTiempoTranscurrido.setBackground(new java.awt.Color(153, 153, 153));
        labelTiempoTranscurrido.setForeground(new java.awt.Color(255, 255, 255));
        labelTiempoTranscurrido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panel2.setBackground(new java.awt.Color(51, 51, 51));
        panel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel2.setAlignmentX(0.1F);
        panel2.setAlignmentY(0.1F);

        btnAbrir.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        btnAbrir.setText("...");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        labelCaptura.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        labelCaptura.setForeground(new java.awt.Color(255, 255, 255));
        labelCaptura.setText("Abrir Archivo:");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCaptura)
                .addGap(30, 30, 30)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCaptura)
                    .addComponent(btnAbrir))
                .addContainerGap())
        );

        labelTiempoTotal.setBackground(new java.awt.Color(153, 153, 153));
        labelTiempoTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTiempoTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtCiudad.setEnabled(false);
        txtCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCiudadFocusGained(evt);
            }
        });
        txtCiudad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtCiudadInputMethodTextChanged(evt);
            }
        });
        txtCiudad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCiudadPropertyChange(evt);
            }
        });
        txtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCiudadKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Renombrar Ciudad:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Renombrar Calle:");

        txtCalle.setEnabled(false);
        txtCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCalleFocusGained(evt);
            }
        });
        txtCalle.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtCalleInputMethodTextChanged(evt);
            }
        });
        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });
        txtCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCalleKeyPressed(evt);
            }
        });

        btnAceptarCiudad.setText("Renombrar");
        btnAceptarCiudad.setEnabled(false);
        btnAceptarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCiudadActionPerformed(evt);
            }
        });

        btnAceptarCalle.setText("Renombrar");
        btnAceptarCalle.setEnabled(false);
        btnAceptarCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAceptarCalleFocusGained(evt);
            }
        });
        btnAceptarCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTiempoTranscurrido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTiempoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAceptarCiudad))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(48, 48, 48)
                                            .addComponent(btnAceptarCalle))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(barraProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(labelTiempoTranscurrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelTiempoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptarCiudad))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptarCalle))
                        .addGap(79, 79, 79)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(btnParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReproducir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirActionPerformed
        
        if (!VideoService.getControladorVideo().isStartButtonClicked() && 
             VideoService.getControladorVideo().isPauseVideo()) {
            VideoService.getControladorVideo().setStartButtonClicked(true);
            VideoService.getControladorVideo().setPauseVideo(false);
            btnParar.setEnabled(true);
            this.btnReproducir.setText("Pausa");
            VideoService.getControladorVideo().startProcessing(this);
            btnAbrir.setEnabled(false);
        } else if (!VideoService.getControladorVideo().isPauseVideo()) {
            VideoService.getControladorVideo().setPauseVideo(true);
            this.btnReproducir.setText("Reproducir");
        } else if (VideoService.getControladorVideo().isPauseVideo()) {
            VideoService.getControladorVideo().setPauseVideo(false);
            btnAbrir.setEnabled(false);
            this.btnReproducir.setText("Pausa");
        }
        btnGuardar.setEnabled(false);
    }//GEN-LAST:event_btnReproducirActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed

        VideoService.getControladorVideo().setStartButtonClicked(false);
        VideoService.getControladorVideo().setPauseVideo(true);
        btnParar.setEnabled(false);
        btnReproducir.setEnabled(true);
        btnReproducir.setText("Reproducir");
        btnAbrir.setEnabled(true);
        VideoService.getControladorVideo().stop();
        setBarrarProgreso(0);
        try {
            VideoService.getControladorVideo().loadVideo();
            txtVideo.setText(VideoService.getControladorVideo().getVideo().toString());
            setTiempo();
        } catch (IOException ex) {
            Logger.getLogger(RegistroVideo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPararActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed

        VideoService.setControladorVideo(new ControladorVideo(this.panel1));
        if (!VideoService.getControladorVideo().isPauseVideo()) {
            VideoService.getControladorVideo().setPauseVideo(true);
            this.btnReproducir.setText("Reproducir");
            btnReproducir.setEnabled(false);
            btnParar.setEnabled(false);
            btnGuardar.setEnabled(false);
        }
        VideoService.getControladorVideo().setPathArchivo((new SeleccionArchivo()).getPathArchivo(this));
        if (VideoService.getControladorVideo().getPathArchivo() != null) {
            btnReproducir.setEnabled(true);
            try {
                VideoService.getControladorVideo().loadVideo();
                txtCiudad.setEnabled(true);
                txtCalle.setEnabled(true);
                txtVideo.setText(VideoService.getControladorVideo().getVideo().toString());
                setTiempo();
            } catch (IOException ex) {
                panel1.repaint();
                txtVideo.setText("\n\t No se ha cargado un video!");
                JOptionPane.showMessageDialog(rootPane, "No se ha cargado un video!");
                btnAbrir.requestFocusInWindow();
                return;
            }
        } else {
            panel1.repaint();
            txtVideo.setText("\n\t No se ha cargado un video!");
            JOptionPane.showMessageDialog(rootPane, "No se ha cargado un video!");
            btnAbrir.requestFocusInWindow();
            return;
        }
        
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        if (VideoService.getControladorVideo() != null)
            VideoService.getControladorVideo().stop();
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_formWindowClosing

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleActionPerformed

    private void btnAceptarCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAceptarCalleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarCalleFocusGained

    private void txtCiudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCiudadFocusGained
        // TODO add your handling code here:      
    }//GEN-LAST:event_txtCiudadFocusGained

    private void txtCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCalleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleFocusGained

    private void txtCiudadInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtCiudadInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadInputMethodTextChanged

    private void txtCalleInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtCalleInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleInputMethodTextChanged

    private void txtCiudadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCiudadPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadPropertyChange

    private void txtCiudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyPressed
        // TODO add your handling code here:
        if (txtCiudad.getText().isEmpty()) {
            btnAceptarCiudad.setEnabled(false);
        } else {
            btnAceptarCiudad.setEnabled(true);
        }
    }//GEN-LAST:event_txtCiudadKeyPressed

    private void txtCalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleKeyPressed
        // TODO add your handling code here:
        if (txtCalle.getText().isEmpty()) {
            btnAceptarCalle.setEnabled(false);
        } else {
            btnAceptarCalle.setEnabled(true);
        }
    }//GEN-LAST:event_txtCalleKeyPressed

    private void btnAceptarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCiudadActionPerformed
        // TODO add your handling code here:
        VideoService.getControladorVideo().getVideo().setCiudad(txtCiudad.getText());
        btnAceptarCiudad.setEnabled(false);
        txtCiudad.setText("");
        txtVideo.setText(VideoService.getControladorVideo().getVideo().toString());
        JOptionPane.showMessageDialog(rootPane, "Ciudad renombrada satisfactoriamente");
        btnAbrir.requestFocusInWindow();
        return;
    }//GEN-LAST:event_btnAceptarCiudadActionPerformed

    private void btnAceptarCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCalleActionPerformed
        // TODO add your handling code here:
        VideoService.getControladorVideo().getVideo().setCalle(txtCalle.getText());
        btnAceptarCalle.setEnabled(false);
        txtCalle.setText("");
        txtVideo.setText(VideoService.getControladorVideo().getVideo().toString());
        JOptionPane.showMessageDialog(rootPane, "Calle renombrada satisfactoriamente");
        btnAbrir.requestFocusInWindow();
        return;
    }//GEN-LAST:event_btnAceptarCalleActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:      
        VideoService.guardarRegistro(VideoService.getControladorVideo().getVideo());
        btnGuardar.setEnabled(false);
        try {
            VideoService.getControladorVideo().loadVideo();
        } catch (IOException ex) {
            Logger.getLogger(ControladorVideo.class.getName()).log(Level.SEVERE, null, ex);
        }
        setEnableBtnReproducir(true);
        JOptionPane.showMessageDialog(rootPane, "Datos guardados satisfactoriamente");
        return;
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroVideo.setDefaultLookAndFeelDecorated(true);
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                } catch (Exception ex) {
                    System.out.println("Failed loading L&F: ");
                    System.out.println(ex);
                    System.out.println("Loading default Look & Feel Manager!");
                }

                new RegistroVideo().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAceptarCalle;
    private javax.swing.JButton btnAceptarCiudad;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnReproducir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCaptura;
    private javax.swing.JLabel labelTiempoTotal;
    private javax.swing.JLabel labelTiempoTranscurrido;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextArea txtVideo;
    // End of variables declaration//GEN-END:variables

}
